=== NesmaHossam/UIUX-Development-ITI/XML/Task1/task1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="library">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="librarian"/>
				<xs:element name="book" minOccurs="1" maxOccurs="2">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="preface"/>
							<xs:element name="parts" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="chapter" minOccurs="1" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="summary"/>
													<xs:element name="sections">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="content"/>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="title" type="xs:string"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="title" type="xs:string"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="title" type="xs:string"/>
						<xs:attribute name="ISBN" type="xs:integer"/>
						<xs:attribute name="Auther" type="xs:string"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="location" type="xs:string"/>
			<xs:attribute name="description" type="xs:string"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== NesmaHossam/UIUX-Development-ITI/XML/Task1/Task1.xml
<?xml version="1.0" encoding="UTF-8"?>
<library location="Ismailia" description="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\ITI 4-Month\XML\Task1\task1.xsd">
	<librarian name="Ahmed"/>
	<!-- book1-->
	<book title="English" ISBN="32" Auther="Mohamed">
		<preface introduction="NENO"/>
		<parts title="English1">
			<!--Ch1-->
			<chapter title ="presentSimple">
				<summary/>
				<sections>
					<content><![CDATA[
				
				<P>Lorem, ipsum dolor sit amet consectetur       adipisicing elit. Facere laborum id laboriosam, eius ea cupiditate? Natus, autem, provident maiores obcaecati eius nemo ut libero sed nostrum neque quae facilis inventore?
				</P>]]></content>
				</sections>
			</chapter>
			<!--Ch2-->
			<chapter title="presentSimple">
				<summary/>
				<sections>
					<content><![CDATA[
				
				<P>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Facere laborum id laboriosam, eius ea cupiditate? Natus, autem, provident maiores obcaecati eius nemo ut libero sed nostrum neque quae facilis inventore?</P>]]></content>
				</sections>
			</chapter>
		</parts>
	</book>
	<!-- book2-->
	<book title="English" ISBN="32" Auther="Mohamed">
		<preface introduction="NENO"/>
		<parts title="English1">
			<!-- book2-->
			<chapter title="presentSimple">
				<summary/>
				<sections>
					<content><![CDATA[
				
				<P>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Facere laborum id laboriosam, eius ea cupiditate? Natus, autem, provident maiores obcaecati eius nemo ut libero sed nostrum neque quae facilis inventore?</P>]]></content>
				</sections>
			</chapter>
			<!--Ch2-->
			<chapter title="presentSimple">
				<summary/>
				<sections>
					<content><![CDATA[
				
				<P>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Facere laborum id laboriosam, eius ea cupiditate? Natus, autem, provident maiores obcaecati eius nemo ut libero sed nostrum neque quae facilis inventore?</P>]]></content>
				</sections>
			</chapter>
		</parts>
	</book>
</library>
